### ISSUE TITLE
documentation unusable

### ISSUE THREAD

**Issue by LooOOooM** [nicolas-meilan/neuralDeep#2]
It is not clear at all which parameters have to be given to create, train and test the network.
A Step by step example would help. So far I am sure it is a great program, however for everybody except the developer unusable., which ich kind of sad!

**Comment by nicolas-meilan** [comment]
Hello, I just updated the readme with a examples and a description of the procediments to create a NN, can you make a more accurate feedback of the documentation?. Thank you.
